"""empty message

Revision ID: 08514d64eb7a
Revises: 
Create Date: 2016-12-04 21:31:51.953813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08514d64eb7a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dictionary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('word_alay', sa.String(length=255), nullable=True),
    sa.Column('word_normal', sa.String(length=255), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dictionary')
    # ### end Alembic commands ###
